name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal
      - name: Check code formatting
        run: dotnet format --verify-no-changes
      - name: Read secret
        run: echo "Secret value is ${{ secrets.MY_SECRET }}"
      - name: Simulated deploy
        run: bash ./deploy.sh